### ISSUE TITLE
Bug: can not convert multiple fonts

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_font_conv#110]
If you add multiple fonts to the online converter it fails with this error in the console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'symbols')
    at generate_opts_string (index.js:37907:16)
    at HTMLFormElement.handleSubmit (index.js:37987:22)
```

@neuschaefer, I think it's a regression due to the recent changes. Could you take a look at it?

**Comment by neuschaefer** [comment]
As far as I can see, it's fixed in #108.

**Comment by kisvegabor** [comment]
I confirm that it's fixed by #108. Thank you! 
The online converter is updated.
