### ISSUE TITLE
Can not reproduce. Cloned repo and executed this:

### ISSUE THREAD

**Issue by Pzhaowei** [lvgl/lv_font_conv#69]
Can not reproduce. Cloned repo and executed this:

```sh
./lv_font_conv.js --font OPPOSans_OS_Medium.ttf -r 0x20-0x2c63 --size 32 --format bin --bpp 4 --no-compress -o sans32.font
```

Please, make sure you use latest LTS node.js (v16) and latest convertor version.

_Originally posted by @puzrin in https://github.com/lvgl/lv_font_conv/issues/68#issuecomment-1009642967_

**Comment by Pzhaowei** [comment]
node.js version: node-v16.13.1-x64 (2).msi

![111](https://user-images.githubusercontent.com/96897506/148895400-2834d9fa-3198-4bd6-a463-239d0287c287.png)

lv_font_conv --font OPPOSans_OS_Medium.ttf -r 0x20-0xffff --size 24 --format bin --bpp 4 --no-compress -o sans32.font
Error: error in FT_Load_Glyph: -1
at Object.module.exports.glyph_render (C:\Users\11704\AppData\Roaming\npm\node_modules\lv_font_conv\lib\freetype\index.js:205:20)
at collect_font_data (C:\Users\11704\AppData\Roaming\npm\node_modules\lv_font_conv\lib\collect_font_data.js:100:31)
at async convert (C:\Users\11704\AppData\Roaming\npm\node_modules\lv_font_conv\lib\convert.js:24:19)
at async Object.module.exports.run (C:\Users\11704\AppData\Roaming\npm\node_modules\lv_font_conv\lib\cli.js:300:15)

**Comment by puzrin** [comment]
Couple of notes:

- I reformatted your post. Please, see commonmark doc (fenced blocks), how to format code to be readable (or see edied source above, at least).
- Please, don't duplicate issues. If you have extra info - add to existing one, even if been closed. It can be reopened.
