### ISSUE TITLE
this.src.glyphs.map(...).flat is not a function

### ISSUE THREAD

**Issue by CvRXX** [lvgl/lv_font_conv#73]
When running `lv_font_conv` straight from npm I get the following error:
```
$ env DEBUG=* lv_font_conv --no-compress --no-prefilter --bpp 4 --format lvgl --size 20 --font Roboto-Medium.ttf -r 0x20,0x25,0xB0,0x43,0x46,0x2D,0x30-0x39,0x2E -o font_numbers_medium.c
  font last_id: 18 +0ms
  font minY: 0 +2ms
  font maxY: 16 +0ms
  font glyphIdFormat: 0 +1ms
TypeError: this.src.glyphs.map(...).flat is not a function
    at new Font (/usr/local/lib/node_modules/lv_font_conv/lib/font/font.js:38:99)
    at new LvFont (/usr/local/lib/node_modules/lv_font_conv/lib/writers/lvgl/lv_font.js:16:5)
    at Object.write_images [as lvgl] (/usr/local/lib/node_modules/lv_font_conv/lib/writers/lvgl/index.js:12:16)
    at convert (/usr/local/lib/node_modules/lv_font_conv/lib/convert.js:25:35)
```

**Comment by embeddedt** [comment]
What version of Node.js are you using?

**Comment by CvRXX** [comment]
> What version of Node.js are you using?

v10.19.0

**Comment by embeddedt** [comment]
I think you need at least Node v14.

**Comment by CvRXX** [comment]
That fixed it for me. Would be great if this was added to the README

**Comment by puzrin** [comment]
Any not EOL node version should be ok https://nodejs.org/en/about/releases/ (12+).

I'd recommend latest LTS (16)
